---
# vars file for kubernetes
kubernetes_repo_version: 1.29
kubernetes_patch_version: 1
kubernetes_pod_network_cidr: 10.88.0.0/16

kubernetes_helm_repos:
  - name: projectcalico
    repo_url: "https://docs.tigera.io/calico/charts"
  - name: metallb
    repo_url: "https://metallb.github.io/metallb"

kubernetes_helm_charts:
  - name: calico
    chart: projectcalico/tigera-operator
    namespace: tigera-operator
    version: 3.27.0
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.3

kubernetes_helm_plugins:
  - path: "https://github.com/databus23/helm-diff"
    version: 3.9.4
