---
- name: Restart containerd
  ansible.builtin.systemd_service:
    name: containerd
    state: restarted

- name: Restart kubelet
  ansible.builtin.systemd_service:
    name: kubelet
    state: restarted
